apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceberg
  labels:
    app: iceberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iceberg
  template:
    metadata:
      labels:
        app: iceberg
    spec:
      containers:
      - name: iceberg-service
        image: apache/iceberg:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: iceberg-data
          mountPath: /data
      volumes:
      - name: iceberg-data
        persistentVolumeClaim:
          claimName: iceberg-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: iceberg-service
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: iceberg
