apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs
  template:
    metadata:
      labels:
        app: hdfs
    spec:
      containers:
      - name: namenode
        image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
        ports:
        - containerPort: 8020
        - containerPort: 50070
        volumeMounts:
        - name: hdfs-data
          mountPath: /hadoop/dfs/name
      volumes:
      - name: hdfs-data
        persistentVolumeClaim:
          claimName: hdfs-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-service
spec:
  ports:
  - port: 8020
    targetPort: 8020
  selector:
    app: hdfs
