apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs
  namespace: real-estate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs
  template:
    metadata:
      labels:
        app: hdfs
    spec:
      containers:
      - name: hdfs
        image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: hdfs-data
          mountPath: /data/hdfs
      volumes:
      - name: hdfs-data
        persistentVolumeClaim:
          claimName: hdfs-pvc
