apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  labels:
    app: airflow
spec:
  replicas: {{ .Values.airflow.replicas }}
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: {{ .Values.airflow.image }}
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: "mysql+mysqlconnector://root:{{ .Values.mysql.rootPassword }}@{{ .Values.airflow.mysqlHost }}:3306/{{ .Values.mysql.database }}"
          ports:
            - containerPort: {{ .Values.airflow.port }}
