apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app: spark-master
spec:
  replicas: {{ .Values.spark.masterReplicas }}
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: {{ .Values.spark.masterImage }}
          ports:
            - containerPort: 7077
            - containerPort: 8080
