# spark-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
  namespace: data-pipeline
spec:
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
        - name: spark
          image: bitnami/spark:3.1.2
          ports:
            - containerPort: 8080
