apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
  labels:
    app: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark:latest
        ports:
        - containerPort: 7077
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spark-service
spec:
  type: ClusterIP
  selector:
    app: spark
  ports:
  - protocol: TCP
    port: 7077
    targetPort: 7077
  - protocol: TCP
    port: 8080
    targetPort: 8080
