apiVersion: v1
kind: Service
metadata:
  name: spark-service
spec:
  type: ClusterIP
  selector:
    app: spark
  ports:
    - protocol: TCP
      port: 7077
      targetPort: 7077
    - protocol: TCP
      port: 8080
      targetPort: 8080
