apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: data-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: bde2020/spark-worker:3.1.1-hadoop3.2
          ports:
            - containerPort: 8081
          env:
            - name: SPARK_MODE
              value: "worker"
            - name: SPARK_MASTER
              value: "spark://spark-master:7077"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  namespace: data-pipeline
spec:
  ports:
    - port: 8081
  selector:
    app: spark-worker
  type: ClusterIP
