apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: data-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: apache/airflow:2.6.1
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: mysql+mysqlconnector://root:123456@mysql.data-pipeline.svc.cluster.local:3306/demo
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: airflow
  namespace: data-pipeline
spec:
  selector:
    app: airflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
