apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: data-pipeline
spec:
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: apache/airflow:2.6.1
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: "mysql+mysqlconnector://root:123456@mysql/demo"
          ports:
            - containerPort: 8080
