apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  type: ClusterIP
  selector:
    app: airflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-scheduler-service
spec:
  type: ClusterIP
  selector:
    app: airflow
  ports:
    - protocol: TCP
      port: 8793
      targetPort: 8793
