apiVersion: v1
kind: ConfigMap
metadata:
  name: real-estate-config
  namespace: data-pipeline
data:
  config.yml: 
    hdfs_path: "/data/hdfs"
    iceberg_path: "/data/iceberg"
    database:
      host: "localhost"
      port: 5432
      user: "root"
      password: "123456"