apiVersion: v1
kind: ConfigMap
metadata:
  name: etl-config
data:
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  SPARK_MASTER_URL: "spark://spark-service:7077"
  HDFS_NAMENODE: "hdfs://hdfs-service:8020"
  ICEBERG_WAREHOUSE: "/data/warehouse"
