apiVersion: v1
kind: ConfigMap
metadata:
  name: real-estate-config
  namespace: real-estate
data:
  config.yml: |
    hdfs_path: "/data/hdfs"
    iceberg_path: "/data/iceberg"
    database:
      host: "postgresql"
      port: 5432
      user: "username"
      password: "password"
