apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdfs-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iceberg-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/iceberg-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iceberg-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
