apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs-pv
  namespace: data-pipeline
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdfs-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-pv-claim
  namespace: data-pipeline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iceberg-pv
  namespace: data-pipeline
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/iceberg-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iceberg-pv-claim
  namespace: data-pipeline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
